### ISSUE TITLE
Error while invoking node-sea

### ISSUE THREAD

**Issue by bluin4308** [liudonghua123/node-sea#3]
![image](https://github.com/liudonghua123/node-sea/assets/70215341/d6520d23-4398-4245-a359-73ff91dc0162)
![image](https://github.com/liudonghua123/node-sea/assets/70215341/832773ca-10e6-4241-b725-5c7918a8d829)

**Comment by liudonghua123** [comment]
It seems node v22 has changed this syntax.

> This feature was previously named "Import assertions", and using the assert keyword instead of with. Any uses in code of the prior assert keyword should be updated to use with instead.

https://nodejs.org/api/esm.html#import-attributes.

See also https://stackoverflow.com/questions/70106880/err-import-assertion-type-missing-for-import-of-json-file.

Maybe I need to rewrite this line of code using `readFile` manually, see also https://github.com/eslint/eslint/discussions/15305.

```js
import { readFile } from 'node:fs/promises';
const fileUrl = new URL("package.json", import.meta.url);
const parsedPackageJSON = JSON.parse(await readFile(fileUrl, 'utf8'));
```
